// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4ho8aDSRwYXKE734ZO7wcCMZ5w0yl8w',
    appId: '1:938321704837:web:8863d19da5251e6ddd36ec',
    messagingSenderId: '938321704837',
    projectId: 'crud-58837',
    authDomain: 'crud-58837.firebaseapp.com',
    storageBucket: 'crud-58837.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABP0Z6qm7aeWmuNWhIFqvTSdMRERKimdI',
    appId: '1:938321704837:android:d401f0b0d07c4bb5dd36ec',
    messagingSenderId: '938321704837',
    projectId: 'crud-58837',
    storageBucket: 'crud-58837.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgWfxlzi85ylm8Fn32Fz8vJ-LiTDL2COY',
    appId: '1:938321704837:ios:3483961f2f5daebddd36ec',
    messagingSenderId: '938321704837',
    projectId: 'crud-58837',
    storageBucket: 'crud-58837.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgWfxlzi85ylm8Fn32Fz8vJ-LiTDL2COY',
    appId: '1:938321704837:ios:f29fae13b6847e1bdd36ec',
    messagingSenderId: '938321704837',
    projectId: 'crud-58837',
    storageBucket: 'crud-58837.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
